var g_Administrator = 0;
var inktank = [];
var g_cur_tank_num = 4;
var inkSYM = { 'InkMaz': 'MES0046', 'InkGry': 'MES0049', 'InkCia': 'MES0047', 'InkYel': 'MES0045', 'InkPbu': 'MESD001', 'InkPmz': 'MES0587', 'InkPci': 'MES0588', 'InkRed': 'MES0589', 'InkCop': 'MES0590', 'InkMbk': 'MES0592', 'InkLgy': 'MES0919', 'InkClr': 'MES0375', 'InkCMYK': 'MES0585', 'InkBlk': 'MES0044', 'InkPbk': 'MES0048' };
var inkCOL = ['InkBlk', 'InkCia', 'InkMaz', 'InkYel'];
inktank[0] = [0, 8, 0];
inktank[1] = [1, 0, 0];
inktank[2] = [2, 8, 0];
inktank[3] = [3, 6, 0];
var g_help_url = 'https://rs.ciggws.net/rd.cgi?FNC=RUI_HELP&amp;RES=6&amp;DEV=GX7000+series&amp;CNM_SEP=0&amp;DEV=GX7000+series&amp;SFV=1.0&amp;CTV=1.0&amp;LNG=EN&amp;CTN=SDP%2Fsdp-os.html';
var g_eid_url = 'dummy';
var g_ink_url = 'https://rs.ciggws.net/rd.cgi?FNC=RUI_INK&amp;RES=6&amp;DEV=GX7000+series&amp;CNM_SEP=0&amp;DEV=GX7000+series&amp;LNG=EN&amp;HRI=13';
var g_sup_url = 'http://canon.com/support/';
var g_err_url = 'https://rs.ciggws.net/rd.cgi?FNC=RUI_ERR&amp;RES=6&amp;DEV=GX7000+series&amp;CNM_SEP=0&amp;DEV=GX7000+series&amp;LNG=EN&amp;PDR=6&amp;ERR=NO';
var g_pass_url = 'https://rs.ciggws.net/rd.cgi?FNC=RUI_PASS&amp;RES=6&amp;DEV=GX7000+series&amp;CNM_SEP=0&amp;DEV=GX7000+series&amp;LNG=EN&amp;CTN=PW%2Fpw_certifications.html';
var g_cert_url = 'https://rs.ciggws.net/rd.cgi?FNC=RUI_CERT&amp;RES=6&amp;DEV=GX7000+series&amp;CNM_SEP=0&amp;DEV=GX7000+series&amp;LNG=EN&amp;CTN=PW%2Fpw_security.html';
var g_signal_strength = '0';
var g_link_quality = '0';
var g_err_msg_id = 'HTTP_ERR_DISP_IDLE';
var g_bst_st = '0';
var g_battery_sup = 0;
var g_battery = 1;
var g_battery_rest = 0;
var g_battery_ac = 1;
var g_battery_warning = 0;
var g_battery_usb = 1;
var g_prndoc = '0';
var g_firm_up_date = 0;
var g_micro_ap = 0;
var g_wifi_direct = 0;
var g_nfc_mode = 0;
var g_ipp_over_usb = 0;
var g_network_mode = 'LAN_IF_WIRED';
var g_fax_model = 1;
var g_push_scan = 1;
var g_scanner = 1;
var g_adf = 2;
var g_mobile = 0;
var g_scanto_folder = 1;
var g_lan_if = 'LAN_IF_WIRED';
var g_password_enable = 1;
var g_logon_screen = '0';
var g_ssl_cert_auto_create = 1;
var g_ink_empty = 'OFF';
var g_ink_remaining = 'ON';
var g_color_option = 'NO';
var g_ga_enable = 0;
var g_is_supported_extended_password = 1;
var g_cartridge_rest = [3, 0];