"""Add toner and drum levels

Revision ID: bffc67d74211
Revises: 528c4c6005d2
Create Date: 2026-09-04 09:49:56.638755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bffc67d74211'
down_revision: Union[str, Sequence[str], None] = '528c4c6005d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('printers', sa.Column('toner_level', sa.Integer(), nullable=True))
    op.add_column('printers', sa.Column('drum_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('printers', 'drum_level')
    op.drop_column('printers', 'toner_level')
    # ### end Alembic commands ###
